### PR TITLE
fix validation

### PR DESCRIPTION
**Pull request by donglee-afar**
Use hashmap for acceleration and ensure the true validation score,
score:0.89->0.9435, still lower than the origin paper 0.96

### CODE REVIEW

**Comment by wuyifan18** [comment]
@donglee-afar hi, do you have a try to use the 'list' not 'set' of the dataset when inferencing?

**Comment by donglee-afar** [comment]
@wuyifan18 After 3h30min testing, the result which use the 'list' not 'set' of the dataset is the same as 0.9435, and there is no bug in my new predict code...

**Comment by wuyifan18** [comment]
@donglee-afar I just run it and get the result below. You can try a few more times.
image

**Comment by donglee-afar** [comment]
You are right, after used MultiStepLR strategy and train with some more epoch, the result of model is stable with 0.95~0.952, 
and the val data in your repo seems are a few differences from the original data...
Example, there is only 28 templates in your repo...Maybe you use Drain extract log templates instead of ground truth templates??? 
But this is a minor problem and i will try to implement other log anomaly detection algorithms.
Thank you for your repo to help me know the field quickly!

**Comment by wuyifan18** [comment]
@donglee-afar the data is given by the author in [HERE](https://www.cs.utah.edu/~mind/papers/deeplog_misc.html). I just use it and it is not extracted by me.

**Pull request closed without merging**
